function addNewTodoName() {
    var newTodo = document.getElementById("newToDoInput");
    var newTodoValue = newTodo.value;
    var numberElements = getLength();
    addItem(newTodoValue, "ACTIVE");
    // displayAll();
    createActiveTodo(newTodoValue,numberElements);
    // var todoElement = document.createElement("div");
    // // todoElement.setAttribute("class","todoStatusACTIVE media list-group-item");
    // // todoElement.setAttribute("class","todoStatusACTIVE list-group-item");
    // todoElement.setAttribute("class", "todoStatusACTIVE text-center");
    // todoElement.setAttribute("id", "todoNo" + numberElements);
    // var textBody = document.createElement("h5");
    // textBody.setAttribute("id", "textBody" + numberElements);
    // // textBody.setAttribute("class","media-body");
    // textBody.innerText = newTodoValue;
    // todoElement.appendChild(textBody);
    // // todoElement.innerText = newTodoValue;
    // var editButton = document.createElement("button");
    // var editIcon = document.createElement("i");
    // editIcon.setAttribute("class","fa fa-pencil-square-o");
    // editIcon.setAttribute("aria-hidden","true");
    // editButton.appendChild(editIcon);
    // editButton.setAttribute("id", "editButton" + numberElements);
    // editButton.setAttribute("onclick", "editTodoName(" + numberElements + ")");
    // editButton.setAttribute("class", "btn btn-outline-secondary");
    // var editButtonText = document.createElement("span");
    // editButtonText.innerText = " Edit To Do";
    // editButton.appendChild(editButtonText);
    // todoElement.appendChild(editButton);
    // var completeButton = document.createElement("button");
    // var completeIcon = document.createElement("i");
    // completeIcon.setAttribute("class","fa fa-check");
    // completeIcon.setAttribute("aria-hidden","true");
    // completeButton.appendChild(completeIcon);
    // // completeButton.setAttribute("value","Mark As Complete");
    // completeButton.setAttribute("id", "completeButton" + numberElements);
    // completeButton.setAttribute("onclick", "completeTodo(" + numberElements + ")");
    // completeButton.setAttribute("class", "btn btn-outline-success");
    // var completeButtonText = document.createElement("span");
    // completeButtonText.innerText = " Mark As Complete";
    // completeButton.appendChild(completeButtonText);
    // todoElement.appendChild(completeButton);
    // var deleteButton = document.createElement("button");
    // var deleteIcon = document.createElement("i");
    // deleteIcon.setAttribute("class","fa fa-trash");
    // deleteIcon.setAttribute("aria-hidden","true");
    // deleteButton.appendChild(deleteIcon);
    // deleteButton.setAttribute("onclick", "deleteTodo(" + numberElements + ")");
    // deleteButton.setAttribute("id", "deleteButton" + numberElements);
    // deleteButton.setAttribute("class", "btn btn-outline-danger");
    // var deleteButtonText = document.createElement("span");
    // deleteButtonText.innerText = " Delete";
    // deleteButton.appendChild(deleteButtonText);
    // todoElement.appendChild(deleteButton);
    // var parent = document.getElementById("todos");
    // parent.appendChild(todoElement);
    document.getElementById("newToDoInput").value = null;
}